[versions]
spring-boot = "3.3.5"
lombok = "1.18.34"
obj-storage-oss = "3.8.0"
obj-storage-obs = "3.22.12"
[libraries]
#Spring
"spring-boot-dependencies" = { group = "org.springframework.boot",name = "spring-boot-dependencies", version.ref = "spring-boot" }
"spring-boot-configuration-processor" = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
"spring-boot-autoconfigure" = { group = "org.springframework.boot", name = "spring-boot-autoconfigure" }
"spring-boot-starter-web" = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
"spring-boot-starter-test" = { group = "org.springframework.boot", name = "spring-boot-starter-test" }

#Common
"lombok" = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
"obj-storage-oss" = { group = "com.aliyun.oss", name = "aliyun-sdk-oss", version.ref = "obj-storage-oss" }
"obj-storage-obs" = { group = "com.huaweicloud", name = "esdk-obs-java-bundle", version.ref = "obj-storage-obs" }